version: '3'

services:
  sandbox:
    build: .
    tty: true
    privileged: true
    restart: always
    ports: 
      - "4439:4439"
  sandbox-test:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    privileged: true
    depends_on:
      - sandbox
    command: |
      cd backend
      python3 -m pytest ./backend/tests/test.py
