version: "3.8"

services:
  sandbox:
    build: .
    environment:
      - NUOJ_SANDBOX_ENABLE_CG=${NUOJ_SANDBOX_ENABLE_CG}
    tty: true
    privileged: true
    restart: always
    ports: 
      - "4439:4439"
  sandbox-test:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - NUOJ_SANDBOX_ENABLE_CG=${NUOJ_SANDBOX_ENABLE_CG}
    privileged: true
    depends_on:
      - sandbox
    working_dir: /etc/nuoj-sandbox/backend
    command:
      python3 -m pytest --no-header -vv ./tests/ --cov
  minio-test:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=@nuoj2023
    command: minio server /data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090