name: Docker CI [Disable CG]
on: push
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    env:
      NUOJ_SANDBOX_ENABLE_CG: 0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Check config
      run: docker compose config
    
    - name: Disable SWAP ASLR THS
      run: |
        sudo swapoff -a
        echo "0" | sudo tee /proc/sys/kernel/randomize_va_space
        sudo echo "never" | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
        sudo echo "never" | sudo tee /sys/kernel/mm/transparent_hugepage/defrag
        sudo echo "0" | sudo tee /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
        
    - name: Start containers
      run: docker compose up --build --force-recreate --exit-code-from "sandbox-test" minio-test sandbox-test

    - name: Stop containers
      if: always()
      run: docker compose down -v
