name: Docker CI [Disable CG]
on: push
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    env:
      NUOJ_SANDBOX_ENABLE_CG: 0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Check config
      run: docker compose config

    - name: Start containers
      run: docker compose up --build --exit-code-from "sandbox-test" minio-test sandbox-test

    - name: Stop containers
      if: always()
      run: docker compose down -v
