name: Docker Compose Actions Workflow
on: push
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check Control Group
      run: |
        cd /sys/fs/cgroup/memory
        ls
    
    - name: Disable SWAP
      run:
        swapoff -a
    
    - name: Start containers
      run: docker compose up --build --exit-code-from "sandbox-test" sandbox-test

    - name: Stop containers
      if: always()
      run: docker compose down -v
