name: Docker Compose Actions Workflow
on: push
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check Control Group
      run: |
        cd /sys/fs/cgroup/memory
        ls
    
    - name: Disable SWAP ASLR THS
      run:
        sudo swapoff -a
        sudo echo "0" > /sys/proc/kernel/randomize_va_space
        sudo echo "never" > /sys/kernel/mm/transparent_hugepage/enabled
        sudo echo "never" > /sys/kernel/mm/transparent_hugepage/defrag
        sudo echo "never" > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
    
    - name: Start containers
      run: docker compose up --build --exit-code-from "sandbox-test" sandbox-test

    - name: Stop containers
      if: always()
      run: docker compose down -v
