name: Ubuntu 22.04

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install
      run: make reboot=N

    - name: NuOJ Sandbox Status
      run: sudo systemctl status nuoj-sandbox

    - name: Check NuOJ status
      run: sudo python3 test.py
