name: Ubuntu 18.04

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install
      run: make install
      
    - name: NuOJ Sandbox Status
      run: sudo systemctl status nuoj-sandbox

    - name: NuOJ Sandbox Test
      run: sudo python3 test.py
