name: Ubuntu 22.04

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install
      run: make install

    - name: NuOJ Sandbox Status
      run: sudo systemctl status nuoj-sandbox
    
    - name: fetch 4439 service
      run: sudo lsof -i:4439

    - name: Check NuOJ status
      run: sudo python3 test.py
